### ISSUE TITLE
Launcher crashes in wine

### ISSUE THREAD

**Issue by ChaoticWyrme** [neatodev/BmLauncherAsylumNET6#1]
I just tried running the standalone version on linux under wine, and it crashes immediately, with only 3 lines in the log file:
[bmlauncher_report__08-11-22__11-22-31.log](https://github.com/neatodev/BmLauncherAsylumNET6/files/9967381/bmlauncher_report__08-11-22__11-22-31.log)

I'm running on steamdeck using the heroic launcher, if that helps. I found the old version and that worked completely.

**Comment by neatodev** [comment]
I've commented on this on [Nexusmods](https://www.nexusmods.com/batmanarkhamasylum/mods/117?tab=posts) as well. This is not a launcher issue, but a Wine issue. Their .NET 6 implementation is not fully functional yet. Linux users can just keep using the [.NET Framework 4.8 version of the launcher](https://www.nexusmods.com/batmanarkhamasylum/mods/117?tab=files&file_id=940) (which is also available on Nexusmods).

**Comment by michaelbutler** [comment]
@neatodev  donated a few euros for this project. Really happy with it! Amazing how good this game can look after like 13 years. Playing on Manjaro Linux.
