### ISSUE TITLE
Skipping launcher (with arguments)

### ISSUE THREAD

**Issue by DraakjeYoblama** [neatodev/BmLauncherAsylumNET6#11]
Spider-man remastered gives you an option to skip the launcher by starting the game with -nolauncher argument.

It would be nice if this also supported some way to skip the launcher when I don't want to change any settings.

**Comment by michaelbutler** [comment]
Yes that would be nice. maybe it could just run a click event  on the Start Game after 0.5 seconds if that argument is present.

**Comment by DraakjeYoblama** [comment]
Merged #14
